import {open} from '@op-engineering/op-sqlite';

// Initialize the database
export const db = open({
  name: 'offload.sqlite',
});

export async function setupDatabase() {
  try {
    await db.execute(`
      CREATE TABLE IF NOT EXISTS items (
        id            TEXT PRIMARY KEY,
        content_type  TEXT NOT NULL,       -- 'text' | 'image' | 'link'
        raw_content   TEXT,                -- original text or URL
        preview_text  TEXT,                -- display snippet
        thumbnail_path TEXT,               -- local file path or remote URL for thumbnails
        embedding     BLOB NOT NULL,       -- Float32Array, 768 dims (zeros for unembedded images)
        cluster_id    TEXT,
        created_at    INTEGER NOT NULL
      );
    `);

    await db.execute(`
      CREATE TABLE IF NOT EXISTS clusters (
        id            TEXT PRIMARY KEY,
        name          TEXT,                -- generated by Qwen
        centroid      BLOB NOT NULL,       -- mean vector of all member embeddings
        item_count    INTEGER DEFAULT 0,
        last_updated  INTEGER NOT NULL
      );
    `);

    // Schema migrations -- safe to run multiple times (ALTER TABLE is idempotent via try-catch)
    await runMigrations();

    console.log('[Storage] Database initialized successfully');
  } catch (error) {
    console.error('[Storage] Error initializing database:', error);
    throw error;
  }
}

async function runMigrations() {
  // v1: add source_name column for link items (platform badge)
  try {
    await db.execute('ALTER TABLE items ADD COLUMN source_name TEXT;');
  } catch {
    // Column already exists -- ignore
  }
  // v2: add is_embedded flag so unembedded images can be excluded from search
  try {
    await db.execute('ALTER TABLE items ADD COLUMN is_embedded INTEGER NOT NULL DEFAULT 1;');
  } catch {
    // Column already exists -- ignore
  }
  // v3: add description column for link items (OG description / oEmbed description)
  try {
    await db.execute('ALTER TABLE items ADD COLUMN description TEXT;');
  } catch {
    // Column already exists -- ignore
  }
}

export async function checkSqliteVec() {
  try {
    const result = await db.execute('SELECT vec_version() as version;');
    console.log('[Storage] sqlite-vec version:', result.rows?.[0]?.version);
    return true;
  } catch (error) {
    console.error('[Storage] sqlite-vec is not available:', error);
    return false;
  }
}

/**
 * Helper to convert standard JavaScript number[] to a Uint8Array
 * containing the raw bytes of a Float32Array. This is required
 * by sqlite-vec for BLOB storage.
 */
export function getFloat32Buffer(vector: number[]): Uint8Array {
  const f32 = new Float32Array(vector);
  return new Uint8Array(f32.buffer);
}

/**
 * Insert a new text item with its vector embedding.
 */
export async function insertItem(
  id: string,
  text: string,
  embedding: number[]
) {
  try {
    const buffer = getFloat32Buffer(embedding);
    const preview = text.length > 50 ? text.substring(0, 50) + '...' : text;
    
    await db.execute(
      `INSERT INTO items (id, content_type, raw_content, preview_text, embedding, is_embedded, created_at)
       VALUES (?, ?, ?, ?, ?, 1, ?);`,
      [id, 'text', text, preview, buffer.buffer as ArrayBuffer, Date.now()]
    );
    console.log(`[Storage] Inserted text item ${id}`);
    return true;
  } catch (err) {
    console.error('[Storage] Insert error:', err);
    throw err;
  }
}

/**
 * Insert a link item (URL with fetched metadata) and its embedding.
 */
export async function insertLinkItem(
  id: string,
  url: string,
  meta: {
    title: string;
    description: string;
    thumbnailUrl: string | null;
    sourceName: string;
    embedText: string;
  },
  embedding: number[]
) {
  try {
    const buffer = getFloat32Buffer(embedding);
    const preview = meta.title || url;

    await db.execute(
      `INSERT INTO items
         (id, content_type, raw_content, preview_text, description, thumbnail_path, source_name, embedding, is_embedded, created_at)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, 1, ?);`,
      [
        id,
        'link',
        url,
        preview,
        meta.description ?? null,
        meta.thumbnailUrl ?? null,
        meta.sourceName,
        buffer.buffer as ArrayBuffer,
        Date.now(),
      ]
    );
    console.log(`[Storage] Inserted link item ${id} (${meta.sourceName})`);
    return true;
  } catch (err) {
    console.error('[Storage] insertLinkItem error:', err);
    throw err;
  }
}

/**
 * Insert a shared image item.
 * Stores the local path only -- embedding happens later when the model is implemented.
 * A 768-zero placeholder embedding is stored so the NOT NULL constraint is satisfied.
 */
export async function insertImageItem(
  id: string,
  imagePath: string,
  mimeType: string
) {
  try {
    // Zero-vector placeholder -- will be replaced when image embedding is added
    const zeroEmbedding = new Float32Array(768);
    const buffer = new Uint8Array(zeroEmbedding.buffer);

    await db.execute(
      `INSERT INTO items
         (id, content_type, raw_content, preview_text, thumbnail_path, embedding, is_embedded, created_at)
       VALUES (?, ?, ?, ?, ?, ?, 0, ?);`,
      [
        id,
        'image',
        imagePath,
        mimeType,
        imagePath,
        buffer.buffer as ArrayBuffer,
        Date.now(),
      ]
    );
    console.log(`[Storage] Inserted image item ${id}`);
    return true;
  } catch (err) {
    console.error('[Storage] insertImageItem error:', err);
    throw err;
  }
}

/**
 * Delete a single item by id.
 */
export async function deleteItem(id: string) {
  try {
    await db.execute('DELETE FROM items WHERE id = ?;', [id]);
    console.log(`[Storage] Deleted item ${id}`);
    return true;
  } catch (err) {
    console.error('[Storage] deleteItem error:', err);
    throw err;
  }
}

/**
 * Get all stored items (without the embedding BLOB).
 */
export async function getAllItems() {
  try {
    const res = await db.execute(
      `SELECT id, content_type, raw_content, preview_text, description, thumbnail_path, source_name, is_embedded, created_at
       FROM items
       ORDER BY created_at DESC;`
    );
    return res.rows || [];
  } catch (err) {
    console.error('[Storage] Error fetching items:', err);
    return [];
  }
}

/**
 * Search the database for items similar to the given query embedding.
 * Uses sqlite-vec's vec_distance_cosine() function at the native C layer.
 * Image items without an embedding (is_embedded = 0) are excluded.
 */
export async function searchSimilarItems(queryEmbedding: number[], limit: number = 5) {
  try {
    const buffer = getFloat32Buffer(queryEmbedding);
    
    // vec_distance_cosine returns distance (0 = identical, 2 = opposite)
    // So we ORDER BY score ASC
    const res = await db.execute(
      `
      SELECT id, preview_text, content_type, source_name, thumbnail_path,
             vec_distance_cosine(embedding, ?) AS distance
      FROM items
      WHERE is_embedded = 1
      ORDER BY distance ASC
      LIMIT ?;
      `,
      [buffer.buffer as ArrayBuffer, limit]
    );
    
    return res.rows || [];
  } catch (err) {
    console.error('[Storage] Search error:', err);
    throw err;
  }
}

/**
 * Danger zone: Delete all items.
 */
export async function deleteAllItems() {
  try {
    await db.execute('DELETE FROM items;');
    await db.execute('DELETE FROM clusters;');
    console.log('[Storage] All records deleted');
    return true;
  } catch (err) {
    console.error('[Storage] Delete error:', err);
    throw err;
  }
}
