import {open} from '@op-engineering/op-sqlite';

// Initialize the database
export const db = open({
  name: 'offload.sqlite',
});

export async function setupDatabase() {
  try {
    // Drop existing tables for a clean slate in development
    // await db.executeAsync('DROP TABLE IF EXISTS items;');
    // await db.executeAsync('DROP TABLE IF EXISTS clusters;');

    await db.executeAsync(`
      CREATE TABLE IF NOT EXISTS items (
        id            TEXT PRIMARY KEY,
        content_type  TEXT NOT NULL,       -- 'text' | 'image' | 'link'
        raw_content   TEXT,                -- original text or URL
        preview_text  TEXT,                -- display snippet
        thumbnail_path TEXT,               -- local file path for images/OG images
        embedding     BLOB NOT NULL,       -- Float32Array, 768 dims
        cluster_id    TEXT,
        created_at    INTEGER NOT NULL
      );
    `);

    await db.executeAsync(`
      CREATE TABLE IF NOT EXISTS clusters (
        id            TEXT PRIMARY KEY,
        name          TEXT,                -- generated by Qwen
        centroid      BLOB NOT NULL,       -- mean vector of all member embeddings
        item_count    INTEGER DEFAULT 0,
        last_updated  INTEGER NOT NULL
      );
    `);

    console.log('[Storage] Database initialized successfully');
  } catch (error) {
    console.error('[Storage] Error initializing database:', error);
    throw error;
  }
}

export async function checkSqliteVec() {
  try {
    // Test if sqlite-vec is loaded by calling vec_version()
    const result = await db.executeAsync('SELECT vec_version() as version;');
    console.log('[Storage] sqlite-vec version:', result.rows?._array[0]?.version);
    return true;
  } catch (error) {
    console.error('[Storage] sqlite-vec is not available:', error);
    return false;
  }
}
